### ISSUE TITLE
Add support to giveaway.su

### ISSUE THREAD

**Issue by Rapperk** [longnull/GiveawayCompanion#1]
Sorry if this isnt the right place, but, would it be possible to add support to giveaway.su website?
Its a giveaway website i use a lot, and it would be awesome if the script could work there, at least the bar to join the groups would already help a lot.

It would be awesome. Thanks.

**Comment by longnull** [comment]
Sorry, but no. In my opinion, people should ignore giveaway.su because they require you to install a browser extension that sends source pages (Steam group pages, for example) to the server for verification. They can implement any shit in their extension and users will not notice anything.

Sorry if my English is too bad. 😶

**Comment by notarnas** [comment]
Maybe you could create a seperate script for it or something? That would be really cool, since still a lot of people use it.

**Comment by longnull** [comment]
I can add support for Steam groups, but you will still have to install the extension and complete the tasks manually. Is this OK or useless? 🙂

**Comment by notarnas** [comment]
Sounds great! Looking forward to it :)

**Comment by longnull** [comment]
Done https://github.com/longnull/GiveawayCompanion/commit/48017294f2369ed1b1ba062f2eca00d4c7cc1494

Perhaps in the future I will implement the automatic completion of tasks without their crappy extension. I'll think about it. 🙃

**Comment by longnull** [comment]
I did this shit 😼 628401f3faaf1d0b4de406b1e0e602c33c5fc39d

**Comment by Rapperk** [comment]
![image](https://user-images.githubusercontent.com/42440290/51768554-86512380-20d8-11e9-86cb-d4732aef656a.png)

Well, it was good while it worked, seems that they can detect it now, so, thanks anyway for the update, it was better and safer than using their extension, plus firefox users could do their giveaways with your script, but in my opinion, i think it doesnt worth to keep making updates to fix this, since they will always find a way to "ban" us. I belive the support for the steam groups is enough for this website.

Thank you.

**Comment by notarnas** [comment]
> ![image](https://user-images.githubusercontent.com/42440290/51768554-86512380-20d8-11e9-86cb-d4732aef656a.png)
> 
> Well, it was good while it worked, seems that they can detect it anymore, so, thanks anyway for the update, it was better and safer than using their extension, plus firefox users could do their giveaways on firefox, but in my opinion, i think it doesnt worth to keep making updates to fix this, since they will always find a way to "ban" us. I belive the support for the groups is enough for this website.

I perfectly agree. Thanks so much to the dev.

**Comment by longnull** [comment]
Sadly, I spent a lot of time on it. That's to be expected, but I didn't think they'd react so quickly. I think the main reason is a post (not mine) in VK group about free games, which has 70k hungry subscribers. 😄
