### ISSUE TITLE
gleam.io not working

### ISSUE THREAD

**Issue by arogl** [longnull/GiveawayCompanion#10]
On this page 

[WIN: One Of Five PowerA Nintendo Switch Prize Packs](https://gleam.io/JRbe1/win-one-of-five-powera-nintendo-switch-prize-packs)

I do not see the capability of using the script:

![Gleam.io Capture](https://user-images.githubusercontent.com/1115472/231914725-294eace8-534e-4ab9-a15d-e0a36daff67c.png)

- Browser: Chrome Version 111.0.5563.65 (Official Build) (64-bit) (Windows)
- Extension: Tampermonkey

**Comment by longnull** [comment]
On gleam.io script helps only to join Steam groups, in that giveaway there are no such tasks
