### ISSUE TITLE
Keyjoker.com перестал работать

### ISSUE THREAD

**Issue by 10522** [longnull/GiveawayCompanion#13]
На [этой](https://www.keyjoker.com/entries) странице постоянно появляется и исчезает это окно:

![0900909090](https://github.com/longnull/GiveawayCompanion/assets/59209149/7c35e0c6-0269-462c-9387-0972510d0fb0)

Также, возможно ли добавить выполнение и подтверждение [этих](https://www.keyjoker.com/actions/new) заданий? Например, можно добавить кнопку, которая будет нажимать на все кнопки "REDEEM", т.к. некоторые задания (Twitter, Facebook и возможно ещё какие-то) вообще никак не проверяются и достаточно нажать на кнопку "REDEEM".

- Browser: Google Chrome 123.0.6312.86
- Extension: Tampermonkey

**Comment by longnull** [comment]
> На [этой](https://www.keyjoker.com/entries) странице постоянно появляется и исчезает это окно:

Это происходит из-за капчи от Cloudflare. Проверил в Firefox + Violentmonkey и в Chrome + Tampermonkey и Violentmonkey - в Firefox работает нормально, т.к. в запросах, которые делает скрипт, передаётся куки cf_clearance, а в Chrome почему-то куки нет и в ответ приходит 403. Я не знаю, в чём причина такого поведения Chrome и как это исправить. 🤔

> Также, возможно ли добавить выполнение и подтверждение [этих](https://www.keyjoker.com/actions/new) заданий? Например, можно добавить кнопку, которая будет нажимать на все кнопки "REDEEM", т.к. некоторые задания (Twitter, Facebook и возможно ещё какие-то) вообще никак не проверяются и достаточно нажать на кнопку "REDEEM".

Ссылка ведёт на создание задания. Я так понимаю, имелась в виду та же страница [entries](https://www.keyjoker.com/entries). Посмотрю, возможно, добавлю, если будет нормально работать.

**Comment by longnull** [comment]
Похоже, причина в [этих нововведениях](https://developers.google.com/privacy-sandbox/3pcd/chips?hl=ru). Если вручную удалить у куки атрибут Partition Key, то куки отправляется и капчи нет.

Tampermonkey готовит [решение](https://github.com/Tampermonkey/tampermonkey/issues/2057), а Violentmonkey [ждёт](https://github.com/violentmonkey/violentmonkey/issues/2100).
