### ISSUE TITLE
Doesn't work on all sites

### ISSUE THREAD

**Issue by MAX1MDEV** [longnull/GiveawayCompanion#14]
Browser: Brave
Extension: Tampermonkey
The script does not fully work on giveaway.su, givee.club. 
![image](https://github.com/user-attachments/assets/1cc3c91a-8544-40e5-92e9-fd396a315745)

**Comment by longnull** [comment]
На giveaway.su поддерживаются только группы, на скриншоте, похоже, всё ок. А на givee.club что не работает?

**Comment by MAX1MDEV** [comment]
> На giveaway.su поддерживаются только группы, на скриншоте, похоже, всё ок. А на givee.club что не работает?

На givee.club все ок, я кстати заметил, что большинство сайтов из подборки не работают, может стоит обновиться Read.me?

**Comment by longnull** [comment]
Вроде только два сдохли - gamingimpact.com и key.gift, надо будет убрать их. Какие-то давно без раздач, но пока ещё грузятся, пусть будут пока, не мешают.

**Comment by MAX1MDEV** [comment]
> Вроде только два сдохли - gamingimpact.com и key.gift, надо будет убрать их. Какие-то давно без раздач, но пока ещё грузятся, пусть будут пока, не мешают.

Хорошо, удачного развития проекта ;)
