### ISSUE TITLE
Integrate with Augmented Steam/IsThereAnyDeal to add Wishlist notes

### ISSUE THREAD

**Issue by mat926** [longnull/GiveawayCompanion#16]
Can this integrate with Augmented Steam/IsThereAnyDeal , when adding a game to wishlist is it possible to include a note saying this is for the giveaway?

**Comment by longnull** [comment]
Unfortunately, the script cannot access the extension data

**Comment by mat926** [comment]
> Unfortunately, the script cannot access the extension data

Can you access the API for ITAD to add the notes for the games?

**Comment by longnull** [comment]
The user would need to go through OAuth authorization, the script would need to accept and save the authorization data and then make requests to the API. I don't think it's worth it
