### ISSUE TITLE
Gamehag

### ISSUE THREAD

**Issue by notarnas** [longnull/GiveawayCompanion#2]
The script doesn't seem to work on Gamehag.

**Comment by longnull** [comment]
Yes, I noticed that the script doesn't work if selected English language (oops :). This is already fixed, I'll push the fix today or tomorrow. Thanks.

**Comment by longnull** [comment]
Fixed https://github.com/longnull/GiveawayCompanion/commit/83995d6061d038a9cd4163c3a0e15122e9785522

Please check and confirm. 🙃

**Comment by notarnas** [comment]
Works perfectly.
