### ISSUE TITLE
giveaway.su support patched

### ISSUE THREAD

**Issue by notarnas** [longnull/GiveawayCompanion#3]
Sadly, giveaway.su support got patched really darn quickly. It was good while it lasted. Thank you for the hard work, developer, i still really appreciate it <3

[https://imgur.com/a/rVZSOHZ](url)

**Comment by longnull** [comment]
Sadly, I spent a lot of time on it. That's to be expected, but I didn't think they'd react so quickly. I think the main reason is a post (not mine) in VK group about free games, which has 70k hungry subscribers. 😄

**Comment by psydex** [comment]
Will you fix it?

**Comment by longnull** [comment]
No, I'll remove this functionality in the next version.

**Comment by Saacy** [comment]
Hello, longnull!

I am really sorry about the time you have spent on this. I put a red alert for you and Citrinate several months ago to describe why tasks should be completed: sponsors won't provide new Steam keys if users don't complete tasks.

As you can see - there is no other way to validate the completion of some sponsor's task types (for example, curators tasks). And no other giveaway services can validate such tasks.

Feel free to contact me via longnull[at]giveaway.su if you have any questions, suggestions, improvements or new ideas for our service.

Best wishes.

**Comment by notarnas** [comment]
> Hello, longnull!
> 
> I am really sorry about the time you have spent on this. I put a red alert for you and Citrinate several months ago to describe why tasks should be completed: sponsors won't provide new Steam keys if users don't complete tasks.
> 
> As you can see - there is no other way to validate the completion of some sponsor's task types (for example, curators tasks). And no other giveaway services can validate such tasks.
> 
> Feel free to contact me via longnull[at]giveaway.su if you have any questions, suggestions, improvements or new ideas for our service.
> 
> Best wishes.

Not the author obviously, but the only reason i personally refuse to use the extension is it's SOOO heavy on the permissions. It has access to ALL DATA on ALL SITES, which is pretty insane if you think about it. If you make it so it sees only sites you need, for example Steam/VK/Youtube/Reddit/Twitter etc. It would be a perfectly fine extension and a lot more people would be using it, in my opinion.

**Comment by Saacy** [comment]
The only reason we don't have a strict list of websites (we did have it earlier) - sometimes we add new websites to support new sponsor's tasks (like Reddit or Instagram) and it is a real pain to update extension on Chrome Store (it takes days and weeks to get extension checked by Chrome Store team). I would like to release Tampermonkey version with a strict permissions but there is a problem with Twitter tasks atm.

In Chrome settings you can limit websites the extension has access to. So if you want you can set it up on your own - just go to extension's settings and create a list of websites.

**Comment by notarnas** [comment]
> The only reason we don't have a strict list of websites (we did have it earlier) - sometimes we add new websites to support new sponsor's tasks (like Reddit or Instagram) and it is a real pain to update extension on Chrome Store (it takes days and weeks to get extension checked by Chrome Store team). I would like to release Tampermonkey version with a strict permissions but there is a problem with Twitter tasks atm.
> 
> In Chrome settings you can limit websites the extension has access to. So if you want you can set it up on your own - just go to extension's settings and create a list of websites.

Really looking forward into the Tampermonkey checker. Thanks for the information. And why does the extension need the permission to view my browsing history? Or why does it need access to my Discord connections? Would like to see why you need that too.

**Comment by longnull** [comment]
> Hello, longnull!
> 
> I am really sorry about the time you have spent on this. I put a red alert for you and Citrinate several months ago to describe why tasks should be completed: sponsors won't provide new Steam keys if users don't complete tasks.

Hello! It's ok, we are just on opposite sides of the barricades. 🙃

> As you can see - there is no other way to validate the completion of some sponsor's task types (for example, curators tasks). And no other giveaway services can validate such tasks.

You're right, but I don't think that user data leakage is a good solution. Social tasks can be verified in the same way as Discord tasks. Unverifiable tasks leave unverified or not add them at all.

**Comment by notarnas** [comment]
> > As you can see - there is no other way to validate the completion of some sponsor's task types (for example, curators tasks). And no other giveaway services can validate such tasks.
> 
> You're right, but I don't think that user data leakage is a good solution. Social tasks can be verified in the same way as Discord tasks. Unverifiable tasks leave unverified or not add them at all.


Exactly. Other sites can easily have VK/Twitter/Youtube/Steam Groups verification without any extensions. Only things you can't check (as far as i know) are Instagram, Reddit and Steam Currators. In my opinion, the extension is just unneccesarry, and im waiting for the Tampermonkey script.
