### ISSUE TITLE
Partial MarvelousGA support?

### ISSUE THREAD

**Issue by psydex** [longnull/GiveawayCompanion#4]
![screenshot_1](https://user-images.githubusercontent.com/5594251/51971802-16052200-248b-11e9-81af-1b12585fd7fe.jpg)

Twitter tasks can not be completed.

- Browser: Firefox Quantum
- Extension: Tampermonkey

**Comment by longnull** [comment]
The script does not do subscriptions/likes/reposts, as it is written in the readme. The script bar size can be changed by dragging the bottom border.

**Comment by longnull** [comment]
Twitter users are often repeated, so you can continue following them to complete tasks faster. If you use Twitter and don't want to see unwanted tweets, mute users instead of unfollowing them.
