### ISSUE TITLE
giveaway.su still detecting ad blocker

### ISSUE THREAD

**Issue by DessertArbiter** [longnull/GiveawayCompanion#5]
- Browser: Chrome
- Extension: Violentmonkey
- Adblocker: Adguard for Windows

i installed both the filter and the script

**Comment by longnull** [comment]
There is currently no filter on the list for giveaway.su.
Try this filter (I don't know if such filters work in Adguard):
`giveaway.su##script:inject(abort-on-property-read.js, adjsData)`

If everything is ok, then I will add it to the filter list.

**Comment by DessertArbiter** [comment]
i tried that filter in both adguard and ublock origin but they both say its not valid

**Comment by longnull** [comment]
It's strange. I tested in Chrome v75 + uBlock Origin v1.21.6 and it worked. 🤔

**Comment by DessertArbiter** [comment]
those scripts dont even exist for me

**Comment by longnull** [comment]
abort-on-property-read.js is one of the [internal scripts](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js) in uBlock Origin, the filter should work as is.
