### ISSUE TITLE
gamehag.com anything task doesn't work

### ISSUE THREAD

**Issue by Anutrix** [longnull/GiveawayCompanion#7]
- Browser: Firefox
- Extension: Greasemonkey

**Comment by longnull** [comment]
Oh, I see `Permission denied` error because the script sets the event handler in the internal jQuery. It seems like Greasemonkey works differently in this situation, maybe I should remove it from README. Violentmonkey and Tampermonkey work well.

**Comment by VirtusHostiz** [comment]
> Oh, I see `Permission denied` error because the script sets the event handler in the internal jQuery. It seems like Greasemonkey works differently in this situation, maybe I should remove it from README. Violentmonkey and Tampermonkey work well.

It doesn't seem to work for me specifically on the gamehag site, on other sites like grabfreegame works.

Browser: Google Chrome
Extension: Tempermonkey

**Comment by Anutrix** [comment]
It worked for me with Tampermonkey but not Greasemonkey on Firefox.

**Comment by longnull** [comment]
> It doesn't seem to work for me specifically on the gamehag site, on other sites like grabfreegame works.

Yeap, because on grabfreegame the script doesn't touch internal scripts

> It worked for me with Tampermonkey but not Greasemonkey on Firefox.

👍
\
\
Sorry for the poor testing, Greasemonkey was not the main target
