### ISSUE TITLE
Givee.club support?

### ISSUE THREAD

**Issue by vsaR1SK** [longnull/GiveawayCompanion#9]
Новый сайт от создателей Giveaway.su ([Givee.club](https://givee.club/)) существует уже довольно давно, а поддержки в плагине всё ещё нет.
Не сложно ли реализовать?

**Comment by longnull** [comment]
Вступлений в группу, похоже, там нет, а добавлять в желаемое и подписываться скрипт не умеет. Надо бы добавить этот функционал, а то сейчас и на других сайтах с раздачами требуют кучу добавлений в желаемое и подписок, но времени на скрипт не хватает
